"""replace supplier_name with supplier_id

Revision ID: 0090a9c7be1a
Revises: 43436c10a31c
Create Date: 2024-10-02 22:26:10.679034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0090a9c7be1a'
down_revision = '43436c10a31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'suppliers', ['supplier_id'], ['id'])
        batch_op.drop_column('supplier_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supplier_id')

    # ### end Alembic commands ###
