"""create suppliers table

Revision ID: 43436c10a31c
Revises: cc92d3a5092b
Create Date: 2024-10-02 22:20:56.843946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43436c10a31c'
down_revision = 'cc92d3a5092b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('representative', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('delivery_date')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('delivery_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.alter_column('invoice_date',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=False)

    op.drop_table('suppliers')
    # ### end Alembic commands ###
